export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-28 pb-16 md:pt-36 md:pb-24 space-y-8">
      <div className="border-b border-border pb-6 space-y-2">
        <h1 className="text-3xl font-extrabold text-foreground tracking-tight">Privacy Policy</h1>
        <p className="text-xs text-muted-foreground">Last updated: June 30, 2026</p>
      </div>

      <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
        <p>
          This Privacy Policy describes the limited technical information processed when you browse the Averqon portfolio.
        </p>

        <h2 className="text-lg font-bold text-foreground mt-8">1. Information We Collect</h2>
        <p>
          We may receive limited technical information generated by your visit, including:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Browser, device type, and operating system</li>
          <li>Pages viewed, visit duration, and referring page</li>
          <li>Approximate region and anonymized performance diagnostics</li>
        </ul>

        <h2 className="text-lg font-bold text-foreground mt-8">2. How We Use Your Information</h2>
        <p>
          We use the information we collect to:
        </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Understand which portfolio projects and capabilities are most useful</li>
          <li>Improve the functionality, layout, and user experience of our website</li>
          <li>Comply with regulatory audits and legal guidelines</li>
        </ul>

        <h2 className="text-lg font-bold text-foreground mt-8">3. Data Retention and Security</h2>
        <p>
          Technical analytics are retained only as long as needed to understand site performance and usage. HTTPS and access controls protect this information against unauthorized retrieval.
        </p>

        <h2 className="text-lg font-bold text-foreground mt-8">4. Sharing of Information</h2>
        <p>
          We do not sell or trade visitor information. Limited technical data may be processed by verified hosting and analytics providers strictly to operate and improve this portfolio.
        </p>

        <h2 className="text-lg font-bold text-foreground mt-8">5. Contact Us</h2>
        <p>
          For questions regarding data logs or requests to delete your records, contact us at:{" "}
          <a href="mailto:privacy@averqon.com" className="text-primary hover:underline">
            privacy@averqon.com
          </a>
        </p>
      </div>
    </div>
  );
}
